# Instructions to tell Travis-CI how to build our project

matrix:
  include:
    - language: java
      script:
      - "gradle build"

    - language: node_js
      before_install:
        - "cd project-group-17-frontend/"
        - "npm install"
      script:
        - "npm run build"
