# Instructions to tell Travis-CI how to build our project

matrix:
  include:
    - language: java
      script:
      - "gradle build"

    - language: node_js
      before_script:
        - "echo 'HELLO WORLD HERE!!!'"
        - "pwd"
        - "cd project-group-17-frontend/"
      install:
        - "npm install"
      script:
        - "npm run build"
